#ifndef BURDEN_THREADS_SRC_WORK_COMMON_LOGIC_EXPORTER_H_
#define BURDEN_THREADS_SRC_WORK_COMMON_LOGIC_EXPORTER_H_

#include "module_util.h"

MODULE_EXPORTER_DECL();

#endif // BURDEN_THREADS_SRC_WORK_COMMON_LOGIC_EXPORTER_H_
