#ifndef APP_FRAME_INC_TASK_TYPE_H_
#define APP_FRAME_INC_TASK_TYPE_H_

enum
{
    TASK_TYPE_MIN = 0,
    TASK_TYPE_NORMAL = TASK_TYPE_MIN,

    TASK_TYPE_SEND_TO_CLIENT,
    TASK_TYPE_CLOSE_CONN,

    TASK_TYPE_MAX,
};

#endif // APP_FRAME_INC_TASK_TYPE_H_
