#ifndef HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_HTTP_WS_MSG_DISPATCHER_H_
#define HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_HTTP_WS_MSG_DISPATCHER_H_

#include <map>
#include "http_ws_msg_handler_interface.h"

namespace tcp
{
namespace http_ws
{
MSG_DISPATCHER_DECL
}
}

#endif // HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_HTTP_WS_MSG_DISPATCHER_H_
