#ifndef HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_WEBSOCKET_H_
#define HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_WEBSOCKET_H_

namespace tcp
{
namespace http_ws
{
}
}

#endif // HTTP_WS_THREADS_SRC_RAW_TCP_COMMON_LOGIC_WEBSOCKET_H_
