#ifndef GLOBAL_THREADS_SRC_WORK_LOGIC_EXPORTER_H_
#define GLOBAL_THREADS_SRC_WORK_LOGIC_EXPORTER_H_

#include "module_util.h"

MODULE_EXPORTER_DECL();

#endif // GLOBAL_THREADS_SRC_WORK_LOGIC_EXPORTER_H_
